version: 2.1

jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Ignored
          command: echo Ignored

workflows:
 gh-pages-wf:
   when:
    false
   jobs:
    - build:
        filters:
          branches:
            ignore:
              - gh-pages
